apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: profiler
  namespace: profiler-system
spec:
  hosts:
    - profiling.jia-huang.com
  gateways:
    - istio-system/gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: profiler
            port:
              number: 80
      timeout: 10000ms
