name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login Docker Hub
      run: |
        docker login --username=xyctruth --password=${{ secrets.DOCKER_TOKEN }}
    - name: Build the Docker image
      run: |
       make docker-build IMG=xyctruth/profiler:latest BASE_API_URL=https://api.profiling.jia-huang.com
    - name: Push the Docker image
      run: |
        make docker-push IMG=xyctruth/profiler:latest BASE_API_URL=https://api.profiling.jia-huang.com

